/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlRouteImport } from './routes/pl'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as EnRouteImport } from './routes/en'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WeddingLocalRouteImport } from './routes/wedding.local'
import { Route as WeddingIdRouteImport } from './routes/wedding.$id'
import { Route as PlVenuesRouteImport } from './routes/pl_.venues'
import { Route as PlPrivacyRouteImport } from './routes/pl_.privacy'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as EnVenuesRouteImport } from './routes/en_.venues'
import { Route as EnPrivacyRouteImport } from './routes/en_.privacy'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as WeddingLocalIndexRouteImport } from './routes/wedding.local/index'
import { Route as WeddingIdIndexRouteImport } from './routes/wedding.$id/index'
import { Route as WeddingLocalPlannerRouteImport } from './routes/wedding.local/planner'
import { Route as WeddingIdPlannerRouteImport } from './routes/wedding.$id/planner'

const PlRoute = PlRouteImport.update({
  id: '/pl',
  path: '/pl',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRoute = EnRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WeddingLocalRoute = WeddingLocalRouteImport.update({
  id: '/wedding/local',
  path: '/wedding/local',
  getParentRoute: () => rootRouteImport,
} as any)
const WeddingIdRoute = WeddingIdRouteImport.update({
  id: '/wedding/$id',
  path: '/wedding/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlVenuesRoute = PlVenuesRouteImport.update({
  id: '/pl_/venues',
  path: '/pl/venues',
  getParentRoute: () => rootRouteImport,
} as any)
const PlPrivacyRoute = PlPrivacyRouteImport.update({
  id: '/pl_/privacy',
  path: '/pl/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const EnVenuesRoute = EnVenuesRouteImport.update({
  id: '/en_/venues',
  path: '/en/venues',
  getParentRoute: () => rootRouteImport,
} as any)
const EnPrivacyRoute = EnPrivacyRouteImport.update({
  id: '/en_/privacy',
  path: '/en/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const WeddingLocalIndexRoute = WeddingLocalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WeddingLocalRoute,
} as any)
const WeddingIdIndexRoute = WeddingIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WeddingIdRoute,
} as any)
const WeddingLocalPlannerRoute = WeddingLocalPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => WeddingLocalRoute,
} as any)
const WeddingIdPlannerRoute = WeddingIdPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => WeddingIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/en': typeof EnRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/pl': typeof PlRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/en/privacy': typeof EnPrivacyRoute
  '/en/venues': typeof EnVenuesRoute
  '/invite/$token': typeof InviteTokenRoute
  '/pl/privacy': typeof PlPrivacyRoute
  '/pl/venues': typeof PlVenuesRoute
  '/wedding/$id': typeof WeddingIdRouteWithChildren
  '/wedding/local': typeof WeddingLocalRouteWithChildren
  '/wedding/$id/planner': typeof WeddingIdPlannerRoute
  '/wedding/local/planner': typeof WeddingLocalPlannerRoute
  '/wedding/$id/': typeof WeddingIdIndexRoute
  '/wedding/local/': typeof WeddingLocalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/en': typeof EnRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/pl': typeof PlRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/en/privacy': typeof EnPrivacyRoute
  '/en/venues': typeof EnVenuesRoute
  '/invite/$token': typeof InviteTokenRoute
  '/pl/privacy': typeof PlPrivacyRoute
  '/pl/venues': typeof PlVenuesRoute
  '/wedding/$id/planner': typeof WeddingIdPlannerRoute
  '/wedding/local/planner': typeof WeddingLocalPlannerRoute
  '/wedding/$id': typeof WeddingIdIndexRoute
  '/wedding/local': typeof WeddingLocalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/en': typeof EnRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/pl': typeof PlRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/en_/privacy': typeof EnPrivacyRoute
  '/en_/venues': typeof EnVenuesRoute
  '/invite/$token': typeof InviteTokenRoute
  '/pl_/privacy': typeof PlPrivacyRoute
  '/pl_/venues': typeof PlVenuesRoute
  '/wedding/$id': typeof WeddingIdRouteWithChildren
  '/wedding/local': typeof WeddingLocalRouteWithChildren
  '/wedding/$id/planner': typeof WeddingIdPlannerRoute
  '/wedding/local/planner': typeof WeddingLocalPlannerRoute
  '/wedding/$id/': typeof WeddingIdIndexRoute
  '/wedding/local/': typeof WeddingLocalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/en'
    | '/home'
    | '/login'
    | '/pl'
    | '/auth/callback'
    | '/en/privacy'
    | '/en/venues'
    | '/invite/$token'
    | '/pl/privacy'
    | '/pl/venues'
    | '/wedding/$id'
    | '/wedding/local'
    | '/wedding/$id/planner'
    | '/wedding/local/planner'
    | '/wedding/$id/'
    | '/wedding/local/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/en'
    | '/home'
    | '/login'
    | '/pl'
    | '/auth/callback'
    | '/en/privacy'
    | '/en/venues'
    | '/invite/$token'
    | '/pl/privacy'
    | '/pl/venues'
    | '/wedding/$id/planner'
    | '/wedding/local/planner'
    | '/wedding/$id'
    | '/wedding/local'
  id:
    | '__root__'
    | '/'
    | '/en'
    | '/home'
    | '/login'
    | '/pl'
    | '/auth/callback'
    | '/en_/privacy'
    | '/en_/venues'
    | '/invite/$token'
    | '/pl_/privacy'
    | '/pl_/venues'
    | '/wedding/$id'
    | '/wedding/local'
    | '/wedding/$id/planner'
    | '/wedding/local/planner'
    | '/wedding/$id/'
    | '/wedding/local/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EnRoute: typeof EnRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  PlRoute: typeof PlRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  EnPrivacyRoute: typeof EnPrivacyRoute
  EnVenuesRoute: typeof EnVenuesRoute
  InviteTokenRoute: typeof InviteTokenRoute
  PlPrivacyRoute: typeof PlPrivacyRoute
  PlVenuesRoute: typeof PlVenuesRoute
  WeddingIdRoute: typeof WeddingIdRouteWithChildren
  WeddingLocalRoute: typeof WeddingLocalRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pl': {
      id: '/pl'
      path: '/pl'
      fullPath: '/pl'
      preLoaderRoute: typeof PlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wedding/local': {
      id: '/wedding/local'
      path: '/wedding/local'
      fullPath: '/wedding/local'
      preLoaderRoute: typeof WeddingLocalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wedding/$id': {
      id: '/wedding/$id'
      path: '/wedding/$id'
      fullPath: '/wedding/$id'
      preLoaderRoute: typeof WeddingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pl_/venues': {
      id: '/pl_/venues'
      path: '/pl/venues'
      fullPath: '/pl/venues'
      preLoaderRoute: typeof PlVenuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pl_/privacy': {
      id: '/pl_/privacy'
      path: '/pl/privacy'
      fullPath: '/pl/privacy'
      preLoaderRoute: typeof PlPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en_/venues': {
      id: '/en_/venues'
      path: '/en/venues'
      fullPath: '/en/venues'
      preLoaderRoute: typeof EnVenuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en_/privacy': {
      id: '/en_/privacy'
      path: '/en/privacy'
      fullPath: '/en/privacy'
      preLoaderRoute: typeof EnPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wedding/local/': {
      id: '/wedding/local/'
      path: '/'
      fullPath: '/wedding/local/'
      preLoaderRoute: typeof WeddingLocalIndexRouteImport
      parentRoute: typeof WeddingLocalRoute
    }
    '/wedding/$id/': {
      id: '/wedding/$id/'
      path: '/'
      fullPath: '/wedding/$id/'
      preLoaderRoute: typeof WeddingIdIndexRouteImport
      parentRoute: typeof WeddingIdRoute
    }
    '/wedding/local/planner': {
      id: '/wedding/local/planner'
      path: '/planner'
      fullPath: '/wedding/local/planner'
      preLoaderRoute: typeof WeddingLocalPlannerRouteImport
      parentRoute: typeof WeddingLocalRoute
    }
    '/wedding/$id/planner': {
      id: '/wedding/$id/planner'
      path: '/planner'
      fullPath: '/wedding/$id/planner'
      preLoaderRoute: typeof WeddingIdPlannerRouteImport
      parentRoute: typeof WeddingIdRoute
    }
  }
}

interface WeddingIdRouteChildren {
  WeddingIdPlannerRoute: typeof WeddingIdPlannerRoute
  WeddingIdIndexRoute: typeof WeddingIdIndexRoute
}

const WeddingIdRouteChildren: WeddingIdRouteChildren = {
  WeddingIdPlannerRoute: WeddingIdPlannerRoute,
  WeddingIdIndexRoute: WeddingIdIndexRoute,
}

const WeddingIdRouteWithChildren = WeddingIdRoute._addFileChildren(
  WeddingIdRouteChildren,
)

interface WeddingLocalRouteChildren {
  WeddingLocalPlannerRoute: typeof WeddingLocalPlannerRoute
  WeddingLocalIndexRoute: typeof WeddingLocalIndexRoute
}

const WeddingLocalRouteChildren: WeddingLocalRouteChildren = {
  WeddingLocalPlannerRoute: WeddingLocalPlannerRoute,
  WeddingLocalIndexRoute: WeddingLocalIndexRoute,
}

const WeddingLocalRouteWithChildren = WeddingLocalRoute._addFileChildren(
  WeddingLocalRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EnRoute: EnRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  PlRoute: PlRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  EnPrivacyRoute: EnPrivacyRoute,
  EnVenuesRoute: EnVenuesRoute,
  InviteTokenRoute: InviteTokenRoute,
  PlPrivacyRoute: PlPrivacyRoute,
  PlVenuesRoute: PlVenuesRoute,
  WeddingIdRoute: WeddingIdRouteWithChildren,
  WeddingLocalRoute: WeddingLocalRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
