/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VenueRouteImport } from './routes/venue'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvitationsRouteImport } from './routes/invitations'
import { Route as HallsRouteImport } from './routes/halls'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WeddingIdRouteImport } from './routes/wedding.$id'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as WeddingIdIndexRouteImport } from './routes/wedding.$id/index'
import { Route as WeddingIdRemindersRouteImport } from './routes/wedding.$id/reminders'
import { Route as WeddingIdPlannerRouteImport } from './routes/wedding.$id/planner'
import { Route as WeddingIdInvitationsRouteImport } from './routes/wedding.$id/invitations'
import { Route as VenueHallsIdRouteImport } from './routes/venue.halls.$id'

const VenueRoute = VenueRouteImport.update({
  id: '/venue',
  path: '/venue',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsRoute = InvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => rootRouteImport,
} as any)
const HallsRoute = HallsRouteImport.update({
  id: '/halls',
  path: '/halls',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WeddingIdRoute = WeddingIdRouteImport.update({
  id: '/wedding/$id',
  path: '/wedding/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const WeddingIdIndexRoute = WeddingIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WeddingIdRoute,
} as any)
const WeddingIdRemindersRoute = WeddingIdRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => WeddingIdRoute,
} as any)
const WeddingIdPlannerRoute = WeddingIdPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => WeddingIdRoute,
} as any)
const WeddingIdInvitationsRoute = WeddingIdInvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => WeddingIdRoute,
} as any)
const VenueHallsIdRoute = VenueHallsIdRouteImport.update({
  id: '/halls/$id',
  path: '/halls/$id',
  getParentRoute: () => VenueRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/halls': typeof HallsRoute
  '/invitations': typeof InvitationsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/venue': typeof VenueRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/invite/$token': typeof InviteTokenRoute
  '/wedding/$id': typeof WeddingIdRouteWithChildren
  '/venue/halls/$id': typeof VenueHallsIdRoute
  '/wedding/$id/invitations': typeof WeddingIdInvitationsRoute
  '/wedding/$id/planner': typeof WeddingIdPlannerRoute
  '/wedding/$id/reminders': typeof WeddingIdRemindersRoute
  '/wedding/$id/': typeof WeddingIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/halls': typeof HallsRoute
  '/invitations': typeof InvitationsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/venue': typeof VenueRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/invite/$token': typeof InviteTokenRoute
  '/venue/halls/$id': typeof VenueHallsIdRoute
  '/wedding/$id/invitations': typeof WeddingIdInvitationsRoute
  '/wedding/$id/planner': typeof WeddingIdPlannerRoute
  '/wedding/$id/reminders': typeof WeddingIdRemindersRoute
  '/wedding/$id': typeof WeddingIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/halls': typeof HallsRoute
  '/invitations': typeof InvitationsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/venue': typeof VenueRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/invite/$token': typeof InviteTokenRoute
  '/wedding/$id': typeof WeddingIdRouteWithChildren
  '/venue/halls/$id': typeof VenueHallsIdRoute
  '/wedding/$id/invitations': typeof WeddingIdInvitationsRoute
  '/wedding/$id/planner': typeof WeddingIdPlannerRoute
  '/wedding/$id/reminders': typeof WeddingIdRemindersRoute
  '/wedding/$id/': typeof WeddingIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/halls'
    | '/invitations'
    | '/login'
    | '/onboarding'
    | '/venue'
    | '/auth/callback'
    | '/invite/$token'
    | '/wedding/$id'
    | '/venue/halls/$id'
    | '/wedding/$id/invitations'
    | '/wedding/$id/planner'
    | '/wedding/$id/reminders'
    | '/wedding/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/halls'
    | '/invitations'
    | '/login'
    | '/onboarding'
    | '/venue'
    | '/auth/callback'
    | '/invite/$token'
    | '/venue/halls/$id'
    | '/wedding/$id/invitations'
    | '/wedding/$id/planner'
    | '/wedding/$id/reminders'
    | '/wedding/$id'
  id:
    | '__root__'
    | '/'
    | '/halls'
    | '/invitations'
    | '/login'
    | '/onboarding'
    | '/venue'
    | '/auth/callback'
    | '/invite/$token'
    | '/wedding/$id'
    | '/venue/halls/$id'
    | '/wedding/$id/invitations'
    | '/wedding/$id/planner'
    | '/wedding/$id/reminders'
    | '/wedding/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HallsRoute: typeof HallsRoute
  InvitationsRoute: typeof InvitationsRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  VenueRoute: typeof VenueRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  InviteTokenRoute: typeof InviteTokenRoute
  WeddingIdRoute: typeof WeddingIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/venue': {
      id: '/venue'
      path: '/venue'
      fullPath: '/venue'
      preLoaderRoute: typeof VenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations': {
      id: '/invitations'
      path: '/invitations'
      fullPath: '/invitations'
      preLoaderRoute: typeof InvitationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/halls': {
      id: '/halls'
      path: '/halls'
      fullPath: '/halls'
      preLoaderRoute: typeof HallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wedding/$id': {
      id: '/wedding/$id'
      path: '/wedding/$id'
      fullPath: '/wedding/$id'
      preLoaderRoute: typeof WeddingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wedding/$id/': {
      id: '/wedding/$id/'
      path: '/'
      fullPath: '/wedding/$id/'
      preLoaderRoute: typeof WeddingIdIndexRouteImport
      parentRoute: typeof WeddingIdRoute
    }
    '/wedding/$id/reminders': {
      id: '/wedding/$id/reminders'
      path: '/reminders'
      fullPath: '/wedding/$id/reminders'
      preLoaderRoute: typeof WeddingIdRemindersRouteImport
      parentRoute: typeof WeddingIdRoute
    }
    '/wedding/$id/planner': {
      id: '/wedding/$id/planner'
      path: '/planner'
      fullPath: '/wedding/$id/planner'
      preLoaderRoute: typeof WeddingIdPlannerRouteImport
      parentRoute: typeof WeddingIdRoute
    }
    '/wedding/$id/invitations': {
      id: '/wedding/$id/invitations'
      path: '/invitations'
      fullPath: '/wedding/$id/invitations'
      preLoaderRoute: typeof WeddingIdInvitationsRouteImport
      parentRoute: typeof WeddingIdRoute
    }
    '/venue/halls/$id': {
      id: '/venue/halls/$id'
      path: '/halls/$id'
      fullPath: '/venue/halls/$id'
      preLoaderRoute: typeof VenueHallsIdRouteImport
      parentRoute: typeof VenueRoute
    }
  }
}

interface VenueRouteChildren {
  VenueHallsIdRoute: typeof VenueHallsIdRoute
}

const VenueRouteChildren: VenueRouteChildren = {
  VenueHallsIdRoute: VenueHallsIdRoute,
}

const VenueRouteWithChildren = VenueRoute._addFileChildren(VenueRouteChildren)

interface WeddingIdRouteChildren {
  WeddingIdInvitationsRoute: typeof WeddingIdInvitationsRoute
  WeddingIdPlannerRoute: typeof WeddingIdPlannerRoute
  WeddingIdRemindersRoute: typeof WeddingIdRemindersRoute
  WeddingIdIndexRoute: typeof WeddingIdIndexRoute
}

const WeddingIdRouteChildren: WeddingIdRouteChildren = {
  WeddingIdInvitationsRoute: WeddingIdInvitationsRoute,
  WeddingIdPlannerRoute: WeddingIdPlannerRoute,
  WeddingIdRemindersRoute: WeddingIdRemindersRoute,
  WeddingIdIndexRoute: WeddingIdIndexRoute,
}

const WeddingIdRouteWithChildren = WeddingIdRoute._addFileChildren(
  WeddingIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HallsRoute: HallsRoute,
  InvitationsRoute: InvitationsRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  VenueRoute: VenueRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  InviteTokenRoute: InviteTokenRoute,
  WeddingIdRoute: WeddingIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
