/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RemindersIndexRouteImport } from './routes/reminders/index'
import { Route as PlannerIndexRouteImport } from './routes/planner/index'
import { Route as PlannerRefactorIndexRouteImport } from './routes/planner-refactor/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersIndexRoute = RemindersIndexRouteImport.update({
  id: '/reminders/',
  path: '/reminders/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerIndexRoute = PlannerIndexRouteImport.update({
  id: '/planner/',
  path: '/planner/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRefactorIndexRoute = PlannerRefactorIndexRouteImport.update({
  id: '/planner-refactor/',
  path: '/planner-refactor/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/planner-refactor/': typeof PlannerRefactorIndexRoute
  '/planner/': typeof PlannerIndexRoute
  '/reminders/': typeof RemindersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/planner-refactor': typeof PlannerRefactorIndexRoute
  '/planner': typeof PlannerIndexRoute
  '/reminders': typeof RemindersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/planner-refactor/': typeof PlannerRefactorIndexRoute
  '/planner/': typeof PlannerIndexRoute
  '/reminders/': typeof RemindersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/planner-refactor/' | '/planner/' | '/reminders/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/planner-refactor' | '/planner' | '/reminders'
  id: '__root__' | '/' | '/planner-refactor/' | '/planner/' | '/reminders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlannerRefactorIndexRoute: typeof PlannerRefactorIndexRoute
  PlannerIndexRoute: typeof PlannerIndexRoute
  RemindersIndexRoute: typeof RemindersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders/': {
      id: '/reminders/'
      path: '/reminders'
      fullPath: '/reminders/'
      preLoaderRoute: typeof RemindersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner/': {
      id: '/planner/'
      path: '/planner'
      fullPath: '/planner/'
      preLoaderRoute: typeof PlannerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner-refactor/': {
      id: '/planner-refactor/'
      path: '/planner-refactor'
      fullPath: '/planner-refactor/'
      preLoaderRoute: typeof PlannerRefactorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlannerRefactorIndexRoute: PlannerRefactorIndexRoute,
  PlannerIndexRoute: PlannerIndexRoute,
  RemindersIndexRoute: RemindersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
