import type { PlannerState } from "@/lib/planner/types"
import { DIETARY_LABELS } from "@/lib/planner/types"

interface Props {
  state: PlannerState
}

/**
 * Shown only when printing (window.print() or Ctrl+P).
 * The rest of the app is hidden via `print:hidden` classes.
 */
export function PlannerPrintView({ state }: Props) {
  const unassigned = state.guests.filter((g) => g.tableId === null)

  return (
    <div className="hidden print:block p-8 font-sans text-black">
      {/* Header */}
      <div className="mb-6 border-b pb-4 text-center">
        <h1 className="text-2xl font-bold">{state.weddingName}</h1>
        <p className="mt-1 text-sm text-gray-500">Seating Plan</p>
        <p className="text-xs text-gray-400">
          {state.tables.length} tables ·{" "}
          {state.guests.filter((g) => g.tableId !== null).length}/
          {state.guests.length} guests seated · Generated{" "}
          {new Date().toLocaleDateString("en-GB")}
        </p>
      </div>

      {/* Tables grid */}
      <div className="grid grid-cols-2 gap-6">
        {state.tables.map((table) => {
          const tableGuests = state.guests.filter(
            (g) => g.tableId === table.id,
          )
          return (
            <div key={table.id} className="break-inside-avoid">
              <h2 className="font-semibold text-sm border-b pb-1 mb-1.5 flex justify-between">
                <span>{table.name}</span>
                <span className="text-gray-500 font-normal">
                  {table.shape} · {tableGuests.length}/{table.capacity}
                </span>
              </h2>
              {tableGuests.length === 0 ? (
                <p className="text-xs text-gray-400 italic">No guests assigned</p>
              ) : (
                <ol className="space-y-0.5">
                  {tableGuests.map((g, i) => (
                    <li key={g.id} className="flex items-baseline gap-1 text-xs">
                      <span className="text-gray-400 w-4 tabular-nums shrink-0">
                        {i + 1}.
                      </span>
                      <span>{g.name}</span>
                      {g.dietary !== "none" && (
                        <span className="text-gray-400">
                          ({DIETARY_LABELS[g.dietary]})
                        </span>
                      )}
                    </li>
                  ))}
                </ol>
              )}
            </div>
          )
        })}
      </div>

      {/* Unassigned */}
      {unassigned.length > 0 && (
        <div className="mt-6 border-t pt-4">
          <h2 className="font-semibold text-sm mb-1.5">
            Unassigned Guests ({unassigned.length})
          </h2>
          <ul className="columns-2 space-y-0.5">
            {unassigned.map((g) => (
              <li key={g.id} className="text-xs">
                · {g.name}
                {g.dietary !== "none" && (
                  <span className="text-gray-400 ml-1">
                    ({DIETARY_LABELS[g.dietary]})
                  </span>
                )}
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Footer */}
      <p className="mt-8 text-center text-[10px] text-gray-300">
        Generated by EasyWed
      </p>
    </div>
  )
}
